alias:
  - name: vi
    value: nvim
  - name: vim
    value: nvim
  - name: cat
    value: bat
  - name: ls
    value: 'eza -a --icons --group-directories-first --git'
  - name: ll
    value: 'eza -la --icons --group-directories-first --git'
  - name: tree
    value: 'eza -T --icons'

  - name: sudo
    value: 'sudo '
    if: eq .OS "linux"
  - name: apt
    value: nala
    if: eq .OS "linux"
  - name: grep
    value: rg
    if: eq .OS "linux"

  - name: zip
    value: nanazipc
    if: eq .OS "windows"

  - name: ignore
    type: git
    value: '!gi() { curl -fsSL https://www.toptal.com/developers/gitignore/api/$@ ;}; gi'

env:
  - name: POSH_THEME
    value: '{{ env "POSH_THEMES_PATH" }}/custom/negligible.omp.json'

script:
  - value: |
      load(io.popen('oh-my-posh init {{ .Shell }} --config %POSH_THEME%'):read("*a"))()
    if: match .Shell "cmd"
  - value: |
      Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete
      Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward
      Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward
      oh-my-posh init {{ .Shell }} --config $env:POSH_THEME | Invoke-Expression
    if: match .Shell "pwsh"
  - value: |
      eval "$(oh-my-posh init {{ .Shell }} --config $POSH_THEME)"
    if: match .Shell "bash" "zsh"
