alias:
  - name: vi
    value: nvim
  - name: vim
    value: nvim
  - name: cat
    value: bat
  - name: npm
    value: pnpm

  - name: sudo
    value: 'sudo '
    if: eq .OS "linux"
  - name: apt
    value: nala
    if: eq .OS "linux"
  - name: grep
    value: rg
    if: eq .OS "linux"
  - name: ls
    value: 'eza -a --icons --group-directories-first --git'
    if: eq .OS "linux"
  - name: ll
    value: 'eza -la --icons --group-directories-first --git'
    if: eq .OS "linux"
  - name: tree
    value: eza -T --icons | less
    if: eq .OS "linux"

  - name: tree
    value: eza -T
    if: eq .OS "windows"

  - name: ignore
    type: git
    value: '!gi() { curl -fsSL https://www.toptal.com/developers/gitignore/api/$@ ;}; gi'

env:
  - name: POSH_THEME
    value: '{{ env "POSH_THEMES_PATH" }}/custom/negligible.omp.json'

script:
  - value: |
      Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete
      Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward
      Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward
      oh-my-posh init {{ .Shell }} --config $env:POSH_THEME | Invoke-Expression
    if: match .Shell "pwsh"
  - value: |
      eval "$(oh-my-posh init {{ .Shell }} --config $POSH_THEME)"
    if: match .Shell "bash" "zsh"
  - value: |
      git fetch --quiet
