[[actions]]
Script = [
    "Remove-Item alias:curl",
    'Set-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize -Name AppsUseLightTheme -Value 0',
    'Set-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search -Name SearchBoxTaskbarMode -Value 0 -Type DWord -Force',
    'Set-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Feeds -Name ShellFeedsTaskbarOpenOnHover -Value 0 -Type DWord -Force',
    'Set-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced -Name Hidden -Value 1 -Type DWord -Force',
    'Set-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced -Name HideIcons -Value 1 -Type DWord -Force',
    'Set-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced -Name OnboardUnpinCortana -Value 1 -Type DWord -Force',
    'Set-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced -Name ShowCortanaButton -Value 0 -Type DWord -Force',
    'Set-ItemProperty -Path "HKCU:\Control Panel\Accessibility\StickyKeys" -Name "Flags" -Type String -Value "506"',
    'Set-ItemProperty -Path "HKCU:\Control Panel\Accessibility\ToggleKeys" -Name "Flags" -Type String -Value "58"',
    'Set-ItemProperty -Path "HKCU:\Control Panel\Accessibility\Keyboard Response" -Name "Flags" -Type String -Value "122"',
]

[[actions]]
Script = [
    "ssh-keygen -q -b 2048 -t ed25519 -f $env:USERPROFILE/.ssh/id_ed25519 -N '' -q",
]

[[actions]]
WingetPackage = "M2Team.NanaZip"

[[actions]]
WingetPackage = "Microsoft.PowerToys"

[[actions]]
WingetPackage = "GeekUninstaller.GeekUninstaller"

[[actions]]
WingetPackage = "Microsoft.PowerShell"

[[actions]]
WingetPackage = "Git.Git"
PSModule      = "posh-git"

[[actions]]
WingetPackage = "Neovim.Neovim"

[[actions]]
WingetPackage = "sharkdp.bat"

[[actions]]
WingetPackage = "chrisant996.Clink"

[[actions]]
WingetPackage = "dotPDNLLC.paintdotnet"

[[actions]]
WingetPackage = "Microsoft.VisualStudioCode"
WingetFlags   = "--interactive"

[[actions]]
WingetPackage     = "Google.Chrome"
DontIncludeUpdate = true

[[actions]]
WingetPackage     = "Spotify.Spotify"
DontIncludeUpdate = true

[[actions]]
WingetPackage = "Spicetify.Spicetify"
DontIncludeUpdate = true
Script = [
    'spicetify config extensions webnowplaying.js',
    'spicetify config custom_apps new-releases',
    'spicetify backup apply',
]

# customizing
[[actions]]
Profile = "customizing"
WingetPackage = "JanDeDobbeleer.OhMyPosh"
Script = [
    'oh-my-posh font install CodeNewRoman --user',
    'oh-my-posh font install FiraCode --user',
]

[[actions]]
Profile       = "customizing"
WingetPackage = "JanDeDobbeleer.Aliae"

[[actions]]
Profile = "customizing"
WingetPackage = "Rainmeter.Rainmeter"
Script = [
    '$file = "JaxCoreSetup.bat"',
    'curl -fsLO "https://github.com/Jax-Core/jax-core.github.io/releases/latest/download/$file"',
    'Invoke-Expression "./$file"',
]

# personal home setup
[[actions]]
Profile           = "home"
WingetPackage     = "Discord.Discord"
DontIncludeUpdate = true

[[actions]]
Profile       = "home"
WingetPackage = "Google.Drive"

[[actions]]
Profile       = "home"
WingetPackage = "Logitech.GHUB"

[[actions]]
Profile       = "home"
WingetPackage = "Nvidia.GeForceExperience"

[[actions]]
Profile       = "home"
WingetPackage = "Nvidia.Broadcast"

[[actions]]
Profile       = "home"
WingetPackage = "Elgato.StreamDeck"

[[actions]]
Profile       = "home"
WingetPackage = "Elgato.WaveLink"

[[actions]]
Profile       = "home"
WingetPackage = "Iriun.IriunWebcam"

# dev
[[actions]]
Profile = "dev"
WingetPackage = "Docker.DockerDesktop"
WingetFlags = "--interactive"
PSModule = "posh-docker"
PreScript = [
    '[Environment]::SetEnvironmentVariable("WSLENV", $env:WSLENV + ":USERPROFILE/p:POSH_THEMES_PATH/p", "USER")',
    'wsl --install Ubuntu',
]

# gaming
[[actions]]
Profile = "gaming"
WingetPackage = "Valve.Steam"
DontIncludeUpdate = true
Script = [
    # Destiny 2
    'Start-Process steam://install/1085660',
    # Retroarch
    'Start-Process steam://install/1118310',
    # WWZ
    'Start-Process steam://install/699130',
]
